# Generated by Django 4.0.1 on 2022-01-15 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256, unique=True)),
                ('lastname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=256, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=256, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Compaing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateField(auto_created=True)),
                ('date_start', models.DateField(auto_created=True)),
                ('date_created', models.DateField(verbose_name='Дата создания')),
                ('name', models.CharField(max_length=256, verbose_name='Название компании')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Удалено')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='dictStatusRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='Статус заявки')),
            ],
        ),
        migrations.CreateModel(
            name='dictTypeMiracle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('CreadedOn', models.DateTimeField(verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256, unique=True)),
                ('token', models.UUIDField(unique=True)),
                ('lastname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=256, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=256, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=256, verbose_name='Телефон')),
                ('institut', models.CharField(max_length=256, verbose_name='Интститут')),
                ('profile', models.CharField(max_length=256, verbose_name='Направление')),
                ('form', models.CharField(max_length=256, verbose_name='Форма обучения')),
                ('source_finance', models.CharField(max_length=256, verbose_name='Источник финансирования')),
                ('level', models.CharField(max_length=256, verbose_name='Уровень обучения')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('date_create_profile', models.DateField(verbose_name='Дата создания')),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_status', models.CharField(max_length=156, verbose_name='Текущий статус')),
                ('CreatedOn', models.DateTimeField(verbose_name='Дата создания')),
                ('LastUpdate', models.DateTimeField(verbose_name='Последнее изменеиние')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('compaing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.compaing')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.student')),
                ('typeMiracle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dicttypemiracle')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryChangeInfoStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата изменения')),
                ('info_old', models.JSONField()),
                ('info_new', models.JSONField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.student')),
            ],
        ),
        migrations.CreateModel(
            name='dictWinnerPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('CreatedOn', models.DateField()),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('type_miracle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dicttypemiracle')),
            ],
        ),
        migrations.CreateModel(
            name='dictTypeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('CreatedOn', models.DateField()),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('type_miracle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dicttypemiracle')),
            ],
        ),
        migrations.CreateModel(
            name='dictTypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('CreatedOn', models.DateField()),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('type_miracle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dicttypemiracle')),
            ],
        ),
        migrations.CreateModel(
            name='dictStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('CreatedOn', models.DateField()),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('type_miracle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dicttypemiracle')),
            ],
        ),
        migrations.CreateModel(
            name='dictRoleStudentToWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('CreatedOn', models.DateField()),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('type_miracle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dicttypemiracle')),
            ],
        ),
        migrations.CreateModel(
            name='DataInfoMiracle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excellent_mark_pecent', models.IntegerField(default=0, verbose_name='Очкнка(отлично),%')),
                ('linkgradebook', models.FileField(upload_to='uploads/')),
                ('date_event', models.DateField()),
                ('number_of_docs', models.CharField(max_length=256, verbose_name='Номер документа')),
                ('linkDocs', models.FileField(upload_to='uploads/')),
                ('role_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dictrolestudenttowork')),
                ('type_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dicttypeevent')),
                ('type_micacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dicttypemiracle')),
                ('type_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dicttypework')),
                ('winner_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dictwinnerplace')),
            ],
        ),
    ]
