# Generated by Django 4.0.1 on 2022-01-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='admin_exam_point',
            field=models.PositiveIntegerField(default=0, verbose_name='Балл за оценку за экзамены (выставляет админ)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='student_exam_point',
            field=models.PositiveIntegerField(default='0', verbose_name='Оценка за экзамены (выставляет студент)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compaing',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
