# Generated by Django 4.0.1 on 2022-01-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
