# Generated by Django 4.0.1 on 2022-01-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0004_student_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='avatar',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
