# Generated by Django 4.0.1 on 2022-01-18 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0005_admin_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Админ', 'verbose_name_plural': 'Админы'},
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.admin')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.student')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='comments',
            field=models.ManyToManyField(to='scholarshipback.Comments'),
        ),
    ]
