# Generated by Django 4.0.1 on 2022-01-18 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0006_alter_admin_options_comments_request_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.admin'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.student'),
        ),
        migrations.AlterField(
            model_name='request',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 40, 33, 535811), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 40, 33, 535811), verbose_name='Последнее изменеиние'),
        ),
        migrations.AlterField(
            model_name='request',
            name='admin_exam_point',
            field=models.PositiveIntegerField(default=0, verbose_name='Балл за оценку за экзамены (выставляет админ)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='student_exam_point',
            field=models.PositiveIntegerField(default=0, verbose_name='Оценка за экзамены (выставляет студент)'),
        ),
        migrations.CreateModel(
            name='dictLearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('CreatedOn', models.DateField()),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('type_miracle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dicttypemiracle')),
            ],
        ),
    ]
