# Generated by Django 4.0.1 on 2022-01-18 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0007_alter_comments_admin_alter_comments_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictlearningplan',
            name='type_miracle',
        ),
        migrations.AlterField(
            model_name='request',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 42, 3, 475281), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 15, 42, 3, 475281), verbose_name='Последнее изменеиние'),
        ),
    ]
