# Generated by Django 4.0.1 on 2022-01-18 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0008_remove_dictlearningplan_type_miracle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfomiracle',
            name='point',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='data',
            field=models.ManyToManyField(to='scholarshipback.DataInfoMiracle'),
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='date_event',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='role_student',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='type_event',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='type_micacle',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='type_work',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='winner_place',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='request',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 21, 46, 4, 721395), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 21, 46, 4, 721395), verbose_name='Последнее изменеиние'),
        ),
    ]
