# Generated by Django 4.0.1 on 2022-01-20 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0010_learningnominationdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningnominationdata',
            name='student_exam_point',
        ),
        migrations.AlterField(
            model_name='learningnominationdata',
            name='excellent_mark_pecent',
            field=models.IntegerField(default=0, verbose_name='Очкнка(отлично),%'),
        ),
        migrations.AlterField(
            model_name='learningnominationdata',
            name='linkgradebook',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 15, 20, 15, 659208), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 15, 20, 15, 659208), verbose_name='Последнее изменеиние'),
        ),
    ]
