# Generated by Django 4.0.1 on 2022-01-21 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0011_remove_learningnominationdata_student_exam_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='learningPlan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dictlearningplan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learningnominationdata',
            name='linkgradebook',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 20, 22, 12, 520371), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 20, 22, 12, 520371), verbose_name='Последнее изменеиние'),
        ),
    ]
