# Generated by Django 4.0.1 on 2022-01-22 08:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0012_request_learningplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dictLevelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Уровень достижения')),
                ('isDeleted', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 0, 34, 162306))),
                ('DeletedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 10, 0, 34, 162306), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dictProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Достижение')),
                ('isDeleted', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 0, 34, 162306))),
                ('DeletedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 10, 0, 34, 162306), null=True)),
                ('typemiracle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dicttypemiracle')),
            ],
        ),
        migrations.CreateModel(
            name='dictStatusProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус достижения')),
                ('isDeleted', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 0, 34, 162306))),
                ('DeletedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 10, 0, 34, 162306), null=True)),
                ('dictprogress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dictprogress')),
            ],
        ),
        migrations.CreateModel(
            name='dictViewProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид достижения')),
                ('isDeleted', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 0, 34, 162306))),
                ('DeletedOn', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 22, 10, 0, 34, 162306), null=True)),
                ('dictprogress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dictprogress')),
                ('typemiracle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dicttypemiracle')),
            ],
        ),
        migrations.RemoveField(
            model_name='dictrolestudenttowork',
            name='type_miracle',
        ),
        migrations.RemoveField(
            model_name='dictstatusevent',
            name='type_miracle',
        ),
        migrations.DeleteModel(
            name='dictStatusRequest',
        ),
        migrations.RemoveField(
            model_name='dicttypeevent',
            name='type_miracle',
        ),
        migrations.RemoveField(
            model_name='dicttypework',
            name='type_miracle',
        ),
        migrations.RemoveField(
            model_name='dictwinnerplace',
            name='type_miracle',
        ),
        migrations.RenameField(
            model_name='datainfomiracle',
            old_name='role_student',
            new_name='progress',
        ),
        migrations.RenameField(
            model_name='datainfomiracle',
            old_name='type_event',
            new_name='viewprogress',
        ),
        migrations.RemoveField(
            model_name='datainfomiracle',
            name='type_work',
        ),
        migrations.RemoveField(
            model_name='datainfomiracle',
            name='winner_place',
        ),
        migrations.AddField(
            model_name='datainfomiracle',
            name='levelprogress',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datainfomiracle',
            name='name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='datainfomiracle',
            name='statusprogress',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='date_event',
            field=models.DateField(verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='request',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 0, 34, 162306), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 0, 34, 162306), verbose_name='Последнее изменеиние'),
        ),
        migrations.RemoveField(
            model_name='request',
            name='data',
        ),
        migrations.AddField(
            model_name='request',
            name='data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarshipback.datainfomiracle'),
        ),
        migrations.DeleteModel(
            name='dictRoleStudentToWork',
        ),
        migrations.DeleteModel(
            name='dictStatusEvent',
        ),
        migrations.DeleteModel(
            name='dictTypeEvent',
        ),
        migrations.DeleteModel(
            name='dictTypeWork',
        ),
        migrations.DeleteModel(
            name='dictWinnerPlace',
        ),
        migrations.AddField(
            model_name='dictstatusprogress',
            name='dictviewprogress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dictviewprogress'),
        ),
        migrations.AddField(
            model_name='dictstatusprogress',
            name='typemiracle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dicttypemiracle'),
        ),
        migrations.AddField(
            model_name='dictlevelprogress',
            name='dictprogress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dictprogress'),
        ),
        migrations.AddField(
            model_name='dictlevelprogress',
            name='dictstatusprogress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dictstatusprogress'),
        ),
        migrations.AddField(
            model_name='dictlevelprogress',
            name='dictviewprogress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dictviewprogress'),
        ),
        migrations.AddField(
            model_name='dictlevelprogress',
            name='typemiracle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.dicttypemiracle'),
        ),
    ]
