# Generated by Django 4.0.1 on 2022-01-22 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0013_dictlevelprogress_dictprogress_dictstatusprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfomiracle',
            name='linkDocs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dictlevelprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 32, 40, 955604)),
        ),
        migrations.AlterField(
            model_name='dictlevelprogress',
            name='DeletedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dictprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 32, 40, 955604)),
        ),
        migrations.AlterField(
            model_name='dictprogress',
            name='DeletedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dictstatusprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 32, 40, 955604)),
        ),
        migrations.AlterField(
            model_name='dictstatusprogress',
            name='DeletedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dictviewprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 32, 40, 955604)),
        ),
        migrations.AlterField(
            model_name='dictviewprogress',
            name='DeletedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 32, 40, 955604), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 32, 40, 955604), verbose_name='Последнее изменеиние'),
        ),
        migrations.RemoveField(
            model_name='request',
            name='data',
        ),
        migrations.AddField(
            model_name='request',
            name='data',
            field=models.ManyToManyField(to='scholarshipback.DataInfoMiracle'),
        ),
    ]
