# Generated by Django 4.0.1 on 2022-01-22 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0014_alter_datainfomiracle_linkdocs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictlevelprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 58, 20, 440146)),
        ),
        migrations.AlterField(
            model_name='dictprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 58, 20, 440146)),
        ),
        migrations.AlterField(
            model_name='dictstatusprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 58, 20, 440146)),
        ),
        migrations.AlterField(
            model_name='dictviewprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 58, 20, 440146)),
        ),
        migrations.AlterField(
            model_name='request',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 58, 20, 424529), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 10, 58, 20, 424529), verbose_name='Последнее изменеиние'),
        ),
        migrations.RemoveField(
            model_name='request',
            name='data',
        ),
        migrations.AddField(
            model_name='request',
            name='data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarshipback.datainfomiracle'),
        ),
    ]
