# Generated by Django 4.0.1 on 2022-01-26 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0017_student_learningplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaing',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 14, 37, 43, 851978)),
        ),
        migrations.AlterField(
            model_name='compaing',
            name='date_start',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='dictlevelprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 14, 37, 44, 851978)),
        ),
        migrations.AlterField(
            model_name='dictprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 14, 37, 44, 851978)),
        ),
        migrations.AlterField(
            model_name='dictstatusprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 14, 37, 44, 851978)),
        ),
        migrations.AlterField(
            model_name='dictviewprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 14, 37, 44, 851978)),
        ),
        migrations.AlterField(
            model_name='request',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 14, 37, 44, 851978), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 14, 37, 44, 851978), verbose_name='Последнее изменеиние'),
        ),
    ]
