# Generated by Django 4.0.1 on 2022-01-26 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0018_alter_compaing_date_end_alter_compaing_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historychangerequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 18, 57, 40, 882133), verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='historychangerequest',
            name='json',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historychangerequest',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scholarshipback.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compaing',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='compaing',
            name='date_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dictlevelprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 18, 57, 40, 882133)),
        ),
        migrations.AlterField(
            model_name='dictprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 18, 57, 40, 882133)),
        ),
        migrations.AlterField(
            model_name='dictstatusprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 18, 57, 40, 882133)),
        ),
        migrations.AlterField(
            model_name='dictviewprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 18, 57, 40, 882133)),
        ),
        migrations.AlterField(
            model_name='request',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 18, 57, 40, 882133), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 18, 57, 40, 882133), verbose_name='Последнее изменеиние'),
        ),
        migrations.DeleteModel(
            name='HistoryChangeInfoStudent',
        ),
    ]
