# Generated by Django 4.0.1 on 2022-01-26 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0019_historychangerequest_date_historychangerequest_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictlevelprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 19, 11, 32, 991672)),
        ),
        migrations.AlterField(
            model_name='dictprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 19, 11, 32, 991672)),
        ),
        migrations.AlterField(
            model_name='dictstatusprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 19, 11, 32, 991672)),
        ),
        migrations.AlterField(
            model_name='dictviewprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 19, 11, 32, 991672)),
        ),
        migrations.AlterField(
            model_name='historychangerequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 19, 11, 32, 991672), verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='request',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 19, 11, 32, 991672), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 19, 11, 32, 991672), verbose_name='Последнее изменеиние'),
        ),
    ]
