# Generated by Django 4.0.1 on 2022-01-27 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0020_alter_dictlevelprogress_createdon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictlevelprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dictprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dictstatusprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dictviewprogress',
            name='CreatedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historychangerequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='request',
            name='CreatedOn',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='LastUpdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее изменеиние'),
        ),
    ]
