# Generated by Django 4.0.5 on 2022-06-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0021_bigboys_alter_dictlevelprogress_createdon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='joinmma@gmail.com', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='joinmma@gmail.com', max_length=256),
            preserve_default=False,
        ),
    ]
