# Generated by Django 4.0.1 on 2022-02-11 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0021_alter_dictlevelprogress_createdon_and_more'),
        ('scholarshipback', '0021_bigboys_alter_dictlevelprogress_createdon_and_more'),
    ]

    operations = [
    ]
