# Generated by Django 4.0.1 on 2022-06-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0022_admin_email_student_email'),
        ('scholarshipback', '0022_merge_20220211_2315'),
    ]

    operations = [
    ]
