# Generated by Django 4.0.5 on 2022-06-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0022_admin_email_student_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datainfomiracle',
            options={'verbose_name': 'Таблица с данными предоставленные студентом на стипендию', 'verbose_name_plural': 'Таблица с данными предоставленные студентом на стипендию'},
        ),
        migrations.AlterModelOptions(
            name='dictlevelprogress',
            options={'verbose_name': 'Уровень достижения', 'verbose_name_plural': 'Уровень достижения'},
        ),
        migrations.AlterModelOptions(
            name='dictprogress',
            options={'verbose_name': 'Достижения', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='dictstatusprogress',
            options={'verbose_name': 'Статус мероприятия', 'verbose_name_plural': 'Статус мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='dicttypemiracle',
            options={'verbose_name': 'Тип повышенной стипендии', 'verbose_name_plural': 'Тип повышенной стипендии'},
        ),
        migrations.AlterModelOptions(
            name='dictviewprogress',
            options={'verbose_name': 'Вид достижения', 'verbose_name_plural': 'Вид достижения'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
