# Generated by Django 4.0.5 on 2022-07-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0024_compaing_show_student_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='data',
            field=models.ManyToManyField(blank=True, to='scholarshipback.datainfomiracle'),
        ),
    ]
