# Generated by Django 4.0.1 on 2022-07-05 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0023_merge_20220621_0550'),
        ('scholarshipback', '0025_alter_request_data'),
    ]

    operations = [
    ]
