# Generated by Django 4.0.1 on 2023-06-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0026_merge_20220705_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datainfomiracle',
            old_name='levelprogress',
            new_name='level_progress',
        ),
        migrations.RenameField(
            model_name='datainfomiracle',
            old_name='statusprogress',
            new_name='status_progress',
        ),
        migrations.RenameField(
            model_name='datainfomiracle',
            old_name='type_micacle',
            new_name='type_miracle',
        ),
        migrations.RenameField(
            model_name='datainfomiracle',
            old_name='viewprogress',
            new_name='view_progress',
        ),
        migrations.AlterField(
            model_name='request',
            name='data',
            field=models.ManyToManyField(blank=True, to='scholarshipback.DataInfoMiracle'),
        ),
    ]
