# Generated by Django 4.0.1 on 2023-06-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0027_rename_levelprogress_datainfomiracle_level_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictlevelprogress',
            name='typemiracle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dict_level_progress', to='scholarshipback.dicttypemiracle'),
        ),
        migrations.AlterField(
            model_name='dictprogress',
            name='typemiracle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dict_progress', to='scholarshipback.dicttypemiracle'),
        ),
        migrations.AlterField(
            model_name='dictstatusprogress',
            name='typemiracle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dict_status_progress', to='scholarshipback.dicttypemiracle'),
        ),
        migrations.AlterField(
            model_name='dictviewprogress',
            name='typemiracle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dict_view_progress', to='scholarshipback.dicttypemiracle'),
        ),
    ]
