# Generated by Django 4.0.1 on 2023-06-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipback', '0028_alter_dictlevelprogress_typemiracle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfomiracle',
            name='date_event',
            field=models.DateField(blank=True, null=True, verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='level_progress',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='linkDocs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='name',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='number_of_docs',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='point',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='progress',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='status_progress',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='type_miracle',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='datainfomiracle',
            name='view_progress',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
